### ISSUE TITLE
Title: Nextcloud for 0.3.6

### ISSUE THREAD

**Issue by k0gen** [Start9Labs/nextcloud-startos#69]
### Service: Nextcloud
This issue is part of our efforts to ensure that the OS is fully ready for the service when 0.3.6 is launched.

**Current Status:**
- [ ] Works Fine
- [ ] Partial Issues
- [x] Doesn't Work

**Description:**
Nextcloud is currently non-functional in StartOS 0.3.6 and is reporting health check issues.

**Tasks:**
- [ ] Diagnose the root cause of the underlying problems with service initialization.
- [ ] Resolve issues causing health check failures.
- [ ] Perform tests to confirm that Nextcloud operates correctly after fixes are applied.
- [ ] Verify that all features of Nextcloud are working as expected.

**Comment by k0gen** [comment]
### Health check issue:

```
Filesystem I/O Error: No such file or directory (os error 2)
```

Logs

```
2024-08-08T09:08:17+02:00  Initializing finished
2024-08-08T09:08:17+02:00  => Searching for scripts (*.sh) to run, located in the folder: /docker-entrypoint-hooks.d/before-starting
2024-08-08T09:08:17+02:00  [08-Aug-2024 07:08:17] ERROR: failed to open error_log (/proc/self/fd/2): No such device or address (6)
2024-08-08T09:08:17+02:00  [08-Aug-2024 07:08:17] ERROR: failed to post process the configuration
2024-08-08T09:08:17+02:00  [08-Aug-2024 07:08:17] ERROR: FPM initialization failed
2024-08-08T09:08:29+02:00  calendar 4.7.15 installed
2024-08-08T09:08:29+02:00  calendar enabled
2024-08-08T09:08:32+02:00  contacts 5.5.3 installed
2024-08-08T09:08:32+02:00  contacts enabled
2024-08-08T09:08:32+02:00  /usr/local/bin/nextcloud-init.sh: line 48: kill: (240) - No such process
2024-08-08T09:08:32+02:00  Error: docker_entrypoint.sh exited with code 1
2024-08-08T09:08:32+02:00      at ChildProcess.<anonymous> (/usr/lib/startos/init/node_modules/@start9labs/start-sdk/cjs/lib/mainFn/CommandController.js:38:35)
2024-08-08T09:08:32+02:00      at ChildProcess.emit (node:events:519:28)
2024-08-08T09:08:32+02:00      at ChildProcess._handle.onexit (node:internal/child_process:294:12)
2024-08-08T09:08:32+02:00  Filesystem I/O Error: No such file or directory (os error 2)
2024-08-08T09:08:32+02:00  Error: docker_entrypoint.sh exited with code 2
2024-08-08T09:08:32+02:00      at ChildProcess.<anonymous> (/usr/lib/startos/init/node_modules/@start9labs/start-sdk/cjs/lib/mainFn/CommandController.js:38:35)
2024-08-08T09:08:32+02:00      at ChildProcess.emit (node:events:519:28)
2024-08-08T09:08:32+02:00      at ChildProcess._handle.onexit (node:internal/child_process:294:12)
2024-08-08T09:09:02+02:00  Filesystem I/O Error: No such file or directory (os error 2)
2024-08-08T09:09:02+02:00  Error: docker_entrypoint.sh exited with code 2
2024-08-08T09:09:02+02:00      at ChildProcess.<anonymous> (/usr/lib/startos/init/node_modules/@start9labs/start-sdk/cjs/lib/mainFn/CommandController.js:38:35)
2024-08-08T09:09:02+02:00      at ChildProcess.emit (node:events:519:28)
2024-08-08T09:09:02+02:00      at ChildProcess._handle.onexit (node:internal/child_process:294:12)
```
